./evaluate_hw_comp_strategy.sh 1
./evaluate_hw_comp_strategy.sh 2
./evaluate_hw_comp_strategy.sh 3
./evaluate_hw_comp_strategy.sh 4
./evaluate_hw_comp_strategy.sh 5
./evaluate_hw_comp_strategy.sh 6
./evaluate_hw_comp_strategy.sh 7
./evaluate_hw_comp_strategy.sh 8
./evaluate_hw_comp_strategy.sh 9
./evaluate_hw_comp_strategy.sh 10
./evaluate_hw_comp_strategy.sh 11
./evaluate_hw_comp_strategy.sh 12
./evaluate_hw_comp_strategy.sh 13
./evaluate_hw_comp_strategy.sh 14
./evaluate_hw_comp_strategy.sh 15
./evaluate_hw_comp_strategy.sh 16
./evaluate_hw_comp_strategy.sh 17
./evaluate_hw_comp_strategy.sh 18
./evaluate_hw_comp_strategy.sh 19
./evaluate_hw_comp_strategy.sh 20
./evaluate_hw_comp_strategy.sh 21
./evaluate_hw_comp_strategy.sh 22